version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-build-stage
    container_name: api
    volumes:
      - .:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    command: yarn dev

    environment:
      - PORT=${PORT}

      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGO_DB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPIRE_IN=${REDIS_EXPIRE_IN}
      - REDIS_CONNECT_TIMEOUT=${REDIS_CONNECT_TIMEOUT}

      - JWT_SECRET=${JWT_SECRET}

      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
    networks:
      - db-network

  mongo:
    image: mongo:5.0.8-focal
    container_name: mongo
    volumes:
      - .docker/data/db:/data/db
      - .docker/db-entrypoint.sh:/docker-entrypoint-initdb.d/db-entrypoint.sh
    restart: unless-stopped
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
    ports:
      - '${MONGO_DB_PORT}:${MONGO_DB_PORT}'
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
