version: '3.8'

services:
  # Nginx service
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - db-network

  # Express service
  server:
    container_name: server
    build:
      context: .
      target: development-build-stage
      dockerfile: Dockerfile
    volumes:
      - .:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
      - /app/node_modules
    environment:
      - PORT=${PORT}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    ports:
      - '${PORT}:${PORT}'
    restart: 'unless-stopped'
    depends_on:
      - mongodb
    networks:
      - db-network

  # Mongodb service
  mongodb:
    image: mongo:5.0.8-focal
    container_name: mongodb
    volumes:
      - .docker/data/db:/data/db
    restart: 'unless-stopped'
    environment:
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    ports:
      - '${MONGO_DB_PORT}:${MONGO_DB_PORT}'
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
